// Namespace: App
public class GameCalculator : SystemCalculatorInstance<GameCalculator> // TypeDefIndex: 9535
{
	// Methods

	// RVA: -1 Offset: -1
	public void AddCommandWithReverse<T>() { }
	/* GenericInstMethod :
	|
	|-RVA: 0x22B4ED0 Offset: 0x22B4FD1 VA: 0x22B4ED0
	|-GameCalculator.AddCommandWithReverse<object>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ActionCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.AroundGenderCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.AttackAttributeCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.AttackCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.AttackCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.AvoidCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BattleAliveCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BattleDeadCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BattleLastTargetCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BattleReviveCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BattleSideCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BattleStyleCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BattleTimesCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BlowDistanceCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.BlowRatioCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ContinuousCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.CriticalCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.DamageCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.DefCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.DefenseCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.DropItemRatioCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.EngageCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.EngageCountLimitCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ExpBattleGiveCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ExpCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ExpDanceCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ExpDestroyCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ExpInterferenceCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ExpRodCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.FixedEnemyCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.FixedFriendCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ForceCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.GainExpCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.GainGoldCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.GenderCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.GodEngagingCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.GodGoodWeaponCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.GodLevelCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.GodSkillCorrectCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.HPCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.HealCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.HitCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.InternalLevelCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.JobInternalLevelCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.JobRankCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.LevelCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.LuukCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.MagicCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.MapPhaseCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.MaxHPCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.MdefCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.MoveDistanceCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.MoveTypeCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.OverlapCanRemoveCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.PhysCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.PickupItemCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.PosLowXCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.PosLowZCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.PosXCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.PosZCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ProbabilityGodSkillCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ProbabilitySkillCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.QuickCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.RangeEnemyCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.RangeFriendCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.RangeGenderCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.RangeUnitCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.ReciveAttackCountCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.RelianceAroundTotalCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.RodExpCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.RodTypeCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SecureCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SimpleCriticalCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SimpleHitCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SimplePowerCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SkillCorrectCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.StrCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SupportAvoidCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SupportCriticalCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SupportHitCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SupportLevelCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.SupportSecureCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TechCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TemporaryCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TerrainAvoidCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TerrainDefenseCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TotalActionCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TotalAttackCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TotalDamageCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TotalLevelCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TotalOrderCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.TotalResultCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitAroundCountdCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitAttackCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitAttributeCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitDefenseCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitGodCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitIdentCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitJobCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitPersonCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.UnitSkillCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponAttackCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponAttributeCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponAvoidCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponCriticalCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponEfficacyCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponEnduranceCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponExpendCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponHitCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponInteractCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponKindCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponLevelCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponSecureCommand>
	|-GameCalculator.AddCommandWithReverse<UnitCalculator.WeaponWeightCommand>
	*/

	// RVA: 0x26A2090 Offset: 0x26A2191 VA: 0x26A2090
	public void .ctor() { }
}

