// Namespace: NexPlugin
public static class Matchmake // TypeDefIndex: 14968
{
	// Fields
	public const uint INVALID_GATHERINGID = 0;
	public const uint NUM_MATCHMAKE_SESSION_ATTRIBUTES = 6;
	public const uint MATCHMAKE_SESSION_NEAREST_NEIGHBOR_ATTRIBUTE_INDEX = 1;
	public const uint MATCHMAKE_SESSION_BROADEN_RANGE_ATTRIBUTE_INDEX = 1;
	public const ulong INVALID_PERSISTENT_GATHERING_CODE = 0;
	public const uint PERSISTENT_GATHERING_CREATION_MAX = 4;
	public const uint PERSISTENT_GATHERING_PARTICIPATION_MAX = 16;
	public const ulong PERSISTENT_GATHERING_CHAT_PARTICIPANTS_MAX = 32;
	public const uint SETATTIBUTE_VECTOR_SIZE_MAX = 100;
	public const byte MAX_PROGRESS_SCORE = 100;
	public const uint UPDATE_PROGRESS_SCORE_MINIMUM_INTERVAL_TIME = 30;
	public const uint MAX_MATCHMAKE_SESSION_USER_PASSWORD_LENGTH = 32;
	public const uint MATCHMAKE_SESSION_SYSTEM_PASSWORD_LENGTH = 16;
	public const uint MAX_MATCHMAKE_BROWSE_SIZE = 100;
	public const uint MAX_PRINCIPALID_SIZE_TO_FIND_MATCHMAKE_SESSION = 300;
	public const uint MAX_MATCHMAKE_BROWSE_SIZE_BY_PARTICIPANT = 300;
	public const uint MAX_MATCHMAKE_SESSION_BY_PARTICIPANT = 1000;
	public const uint MAX_EXTRA_PARTICIPANTS = 4;
	public const uint MAX_P2P_SIGNATURE_KEY_LEN = 32;
	public const ulong RESULTRANGE_ANY_OFFSET = 4294967295;
	public const uint MATCHMAKE_STRING_MAX_LENGTH = 256;
	public const uint MATCHMAKE_BUFFER_MAX_LENGTH = 512;
}

